// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBveznorFBLOpe3KSQZUHJssmFvCxhHr0A',
    appId: '1:201361767014:web:6bea5e019b2a1a117f8ba7',
    messagingSenderId: '201361767014',
    projectId: 'netflix-83a2c',
    authDomain: 'netflix-83a2c.firebaseapp.com',
    storageBucket: 'netflix-83a2c.appspot.com',
    measurementId: 'G-PXSHJQF4MW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmfPe-VgrVaIlcMnvn-YuVrz_Zg8t_Z54',
    appId: '1:201361767014:android:eabc01cede3a48707f8ba7',
    messagingSenderId: '201361767014',
    projectId: 'netflix-83a2c',
    storageBucket: 'netflix-83a2c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVbMDzTTLMvKIwE7ObffZ1-CHQWIGuSIQ',
    appId: '1:201361767014:ios:be31e8bf800f36397f8ba7',
    messagingSenderId: '201361767014',
    projectId: 'netflix-83a2c',
    storageBucket: 'netflix-83a2c.appspot.com',
    iosClientId:
        '201361767014-7vsg4n8if63prs747hgt6n26tr8lc27i.apps.googleusercontent.com',
    iosBundleId: 'com.example.wattflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVbMDzTTLMvKIwE7ObffZ1-CHQWIGuSIQ',
    appId: '1:201361767014:ios:be31e8bf800f36397f8ba7',
    messagingSenderId: '201361767014',
    projectId: 'netflix-83a2c',
    storageBucket: 'netflix-83a2c.appspot.com',
    iosClientId:
        '201361767014-7vsg4n8if63prs747hgt6n26tr8lc27i.apps.googleusercontent.com',
    iosBundleId: 'com.example.wattflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBveznorFBLOpe3KSQZUHJssmFvCxhHr0A',
    appId: '1:201361767014:web:6a012fa12cadb5d57f8ba7',
    messagingSenderId: '201361767014',
    projectId: 'netflix-83a2c',
    authDomain: 'netflix-83a2c.firebaseapp.com',
    storageBucket: 'netflix-83a2c.appspot.com',
    measurementId: 'G-DS3JH2FP3V',
  );
}
